version: "3.1"
services:
  db-omnichat:
    image: mongo
    restart: always
    container_name: db-omnichat
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
  api-omnichat:
    build: .
    image: api-omnichat:hml
    restart: on-failure
    container_name: api-omnichat
    ports:
      - 3000:3000
    environment:
      NODE_ENV: hml
